# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e9b55dc209c9e33fb411c153a11344b831fb05b99fcfb41c2439758abb5c8829042b56b21c70a20cb0705e71ffd9bd06d969a56c3ab6bdb9872821394261ce

test:
  secret_key_base: f1bf68f7d3df21ac8ed3ac8697af81d6272ed34a380dc40b5981f7b734ff2f25a0b35102058a82b144cefd46df927e6b218745329547ca9d75bee7d394e5a23f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
